export const NODE_NAMES = {
    content: 'office:document-content',
    styles: 'office:automatic-styles',
    p: 'text:p',
    span: 'text:span',
    h: 'text:h',
    list: 'text:list',
    ul: 'text:list',
    ol: '',
    li: 'text:list-item',
    decls: 'text:sequence-decls',
    body: 'office:body',
    text: 'text',
    table: 'table:table',
    tr: 'table:table-row',
    td: 'table:table-cell',
    frame: 'draw:frame',
    image: 'draw:image',
};
